// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: feed.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Feed_Feed_FullMethodName                             = "/feed.service.v1.Feed/Feed"
	Feed_GetPublishedVideoByUserId_FullMethodName        = "/feed.service.v1.Feed/GetPublishedVideoByUserId"
	Feed_GetUserFavoriteVideoListByUserId_FullMethodName = "/feed.service.v1.Feed/GetUserFavoriteVideoListByUserId"
)

// FeedClient is the client API for Feed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedClient interface {
	Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	GetPublishedVideoByUserId(ctx context.Context, in *GetPublishedVideoByUserIdRequest, opts ...grpc.CallOption) (*GetPublishedVideoByUserIdResponse, error)
	GetUserFavoriteVideoListByUserId(ctx context.Context, in *GetUserFavoriteVideoListByUserIdRequest, opts ...grpc.CallOption) (*GetUserFavoriteVideoListByUserIdResponse, error)
}

type feedClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedClient(cc grpc.ClientConnInterface) FeedClient {
	return &feedClient{cc}
}

func (c *feedClient) Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, Feed_Feed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetPublishedVideoByUserId(ctx context.Context, in *GetPublishedVideoByUserIdRequest, opts ...grpc.CallOption) (*GetPublishedVideoByUserIdResponse, error) {
	out := new(GetPublishedVideoByUserIdResponse)
	err := c.cc.Invoke(ctx, Feed_GetPublishedVideoByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetUserFavoriteVideoListByUserId(ctx context.Context, in *GetUserFavoriteVideoListByUserIdRequest, opts ...grpc.CallOption) (*GetUserFavoriteVideoListByUserIdResponse, error) {
	out := new(GetUserFavoriteVideoListByUserIdResponse)
	err := c.cc.Invoke(ctx, Feed_GetUserFavoriteVideoListByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedServer is the server API for Feed service.
// All implementations must embed UnimplementedFeedServer
// for forward compatibility
type FeedServer interface {
	Feed(context.Context, *FeedRequest) (*FeedResponse, error)
	GetPublishedVideoByUserId(context.Context, *GetPublishedVideoByUserIdRequest) (*GetPublishedVideoByUserIdResponse, error)
	GetUserFavoriteVideoListByUserId(context.Context, *GetUserFavoriteVideoListByUserIdRequest) (*GetUserFavoriteVideoListByUserIdResponse, error)
	mustEmbedUnimplementedFeedServer()
}

// UnimplementedFeedServer must be embedded to have forward compatible implementations.
type UnimplementedFeedServer struct {
}

func (UnimplementedFeedServer) Feed(context.Context, *FeedRequest) (*FeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Feed not implemented")
}
func (UnimplementedFeedServer) GetPublishedVideoByUserId(context.Context, *GetPublishedVideoByUserIdRequest) (*GetPublishedVideoByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublishedVideoByUserId not implemented")
}
func (UnimplementedFeedServer) GetUserFavoriteVideoListByUserId(context.Context, *GetUserFavoriteVideoListByUserIdRequest) (*GetUserFavoriteVideoListByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFavoriteVideoListByUserId not implemented")
}
func (UnimplementedFeedServer) mustEmbedUnimplementedFeedServer() {}

// UnsafeFeedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedServer will
// result in compilation errors.
type UnsafeFeedServer interface {
	mustEmbedUnimplementedFeedServer()
}

func RegisterFeedServer(s grpc.ServiceRegistrar, srv FeedServer) {
	s.RegisterService(&Feed_ServiceDesc, srv)
}

func _Feed_Feed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).Feed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_Feed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).Feed(ctx, req.(*FeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetPublishedVideoByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishedVideoByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetPublishedVideoByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetPublishedVideoByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetPublishedVideoByUserId(ctx, req.(*GetPublishedVideoByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetUserFavoriteVideoListByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFavoriteVideoListByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetUserFavoriteVideoListByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetUserFavoriteVideoListByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetUserFavoriteVideoListByUserId(ctx, req.(*GetUserFavoriteVideoListByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Feed_ServiceDesc is the grpc.ServiceDesc for Feed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Feed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feed.service.v1.Feed",
	HandlerType: (*FeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Feed",
			Handler:    _Feed_Feed_Handler,
		},
		{
			MethodName: "GetPublishedVideoByUserId",
			Handler:    _Feed_GetPublishedVideoByUserId_Handler,
		},
		{
			MethodName: "GetUserFavoriteVideoListByUserId",
			Handler:    _Feed_GetUserFavoriteVideoListByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feed.proto",
}
