server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  orm:
    dsn: root:uvVFljcDfc2an4U@tcp(mysql:3306)/douyin?charset=utf8mb4&parseTime=True&loc=Local
    active: 100
    idle: 10
    idle_timeout: 10s
  redis:
    name: redis
    network: tcp
    password: uvVFljcDfc2an4U
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    dial_timeout: 0.2s
  kafka:
    addr:
      - kafka:9092
  memcached:
    network: tcp
    addr: memcached:11211
  minio:
    endpoint: minio:9000
    access_key_id: douyin
    secret_access_key: xnQpG8QhRprggUb
registry:
  etcd:
    endpoint: etcd:2379
    dial_timeout: 3s
    time_deviation: 0.5