server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  orm:
    dsn: root:root@tcp(127.0.0.1:3306)/test
    active: 50
    idle: 150
    idle_timeout: 25s
  redis:
    name: video
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
  minio:
    endpoint: 127.0.0.1:9000
    access_key_id: minioadmin
    secret_access_key: minioadmin
  kafka:
    addr:
      - 127.0.0.1:9092
  memcached:
    network: tcp
    addr: 127.0.0.1:11211