// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"douyin/app/seq-server/internal/biz"
	"douyin/app/seq-server/internal/conf"
	"douyin/app/seq-server/internal/data"
	"douyin/app/seq-server/internal/server"
	"douyin/app/seq-server/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEtcdCli(confData, logger)
	dataData, cleanup, err := data.NewData(confData, client, logger)
	if err != nil {
		return nil, nil, err
	}
	seqRepo := data.NewSeqRepo(dataData, logger)
	seqUsecase := biz.NewSeqUsecase(seqRepo, client, bootstrap, logger)
	seqService := service.NewSeqService(seqUsecase)
	grpcServer := server.NewGRPCServer(confServer, seqService, logger)
	httpServer := server.NewHTTPServer(confServer, seqService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
