// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"douyin/app/user/chat/job/internal/biz"
	"douyin/app/user/chat/job/internal/conf"
	"douyin/app/user/chat/job/internal/data"
	"douyin/app/user/chat/job/internal/server"
	"douyin/app/user/chat/job/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewOrm(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	chatRepo := data.NewChatRepo(dataData, logger)
	chatUsecase := biz.NewChatUsecase(chatRepo, logger)
	consumer := data.NewKafka(confData)
	chatService := service.NewChatService(chatUsecase, consumer, logger)
	grpcServer := server.NewGRPCServer(confServer, chatService, logger)
	httpServer := server.NewHTTPServer(confServer, chatService, logger)
	clientv3Client := server.NewEtcdCli(registry)
	registrar := server.NewRegistrar(clientv3Client)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
